# Copyright (C) 2017 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

- name: Reciprocity GGRC
  hosts: all
  pre_tasks:
    - include: roles/common/pre_tasks/main.yml
  roles:
    - ggrc
